/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tienda;

/**
 *
 * @author LIZ
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setVisible(true);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        botonResta6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        botonResta7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        botonResta5 = new javax.swing.JButton();
        txtCantidad5 = new javax.swing.JTextField();
        botonResta1 = new javax.swing.JButton();
        botonSuma1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        botonResta2 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        botonResta3 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        botonResta4 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        botonResta8 = new javax.swing.JButton();
        botonCerrarSesion = new javax.swing.JButton();
        botonCancelarCompra = new javax.swing.JButton();
        txtCantidad1 = new javax.swing.JTextField();
        txtCantidad2 = new javax.swing.JTextField();
        txtCantidad3 = new javax.swing.JTextField();
        txtCantidad4 = new javax.swing.JTextField();
        txtCantidad8 = new javax.swing.JTextField();
        txtCantidad7 = new javax.swing.JTextField();
        txtCantidad6 = new javax.swing.JTextField();
        botonPagar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, -1, -1));

        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));

        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, -1, -1));

        jLabel16.setText("jLabel16");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, -1, -1));

        botonResta6.setText("-");
        botonResta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResta6ActionPerformed(evt);
            }
        });
        jPanel1.add(botonResta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 30, 30));

        jButton2.setText("+");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 30, 30));

        jButton3.setText("+");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, 30, 30));

        botonResta7.setText("-");
        botonResta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResta7ActionPerformed(evt);
            }
        });
        jPanel1.add(botonResta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, 30, 30));

        jButton5.setText("+");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 30, 30));

        botonResta5.setText("-");
        botonResta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResta5ActionPerformed(evt);
            }
        });
        jPanel1.add(botonResta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 30, 30));

        txtCantidad5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad5.setText("0");
        txtCantidad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidad5ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 80, 30));

        botonResta1.setText("-");
        botonResta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResta1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonResta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 30, 30));

        botonSuma1.setText("+");
        botonSuma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSuma1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonSuma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 30, 30));

        jButton9.setText("+");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 30, 30));

        botonResta2.setText("-");
        botonResta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResta2ActionPerformed(evt);
            }
        });
        jPanel1.add(botonResta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 30, 30));

        jButton11.setText("+");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 30, 30));

        botonResta3.setText("-");
        botonResta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResta3ActionPerformed(evt);
            }
        });
        jPanel1.add(botonResta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 30, 30));

        jButton13.setText("+");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 30, 30));

        botonResta4.setText("-");
        botonResta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResta4ActionPerformed(evt);
            }
        });
        jPanel1.add(botonResta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 30, 30));

        jButton29.setText("+");
        jPanel1.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 30, 30));

        botonResta8.setText("-");
        botonResta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResta8ActionPerformed(evt);
            }
        });
        jPanel1.add(botonResta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 30, 30));

        botonCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonCerrarSesion.setText("Cerrar Sesion");
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(botonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 180, 50));

        botonCancelarCompra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonCancelarCompra.setText("Cancelar Compra");
        botonCancelarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarCompraActionPerformed(evt);
            }
        });
        jPanel1.add(botonCancelarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, 180, 50));

        txtCantidad1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad1.setText("0");
        txtCantidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidad1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 80, 30));
        txtCantidad1.getAccessibleContext().setAccessibleParent(this);

        txtCantidad2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad2.setText("0");
        txtCantidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidad2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 80, 30));

        txtCantidad3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad3.setText("0");
        txtCantidad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidad3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 80, 30));

        txtCantidad4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad4.setText("0");
        txtCantidad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidad4ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 80, 30));

        txtCantidad8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad8.setText("0");
        txtCantidad8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidad8ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidad8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, 80, 30));

        txtCantidad7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad7.setText("0");
        txtCantidad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidad7ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidad7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 80, 30));

        txtCantidad6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad6.setText("0");
        txtCantidad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidad6ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidad6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 80, 30));

        botonPagar.setBackground(new java.awt.Color(255, 255, 102));
        botonPagar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonPagar.setText("Proceder a Pagar");
        jPanel1.add(botonPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 580, 180, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceite.jpeg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonResta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResta6ActionPerformed
        // TODO add your handling code here:
       Integer cantidad = Integer.parseInt(txtCantidad6.getText());
       String resultado = String.valueOf(restar(cantidad));
       txtCantidad6.setText(resultado);
    }//GEN-LAST:event_botonResta6ActionPerformed

    private void botonResta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResta7ActionPerformed
        // TODO add your handling code here:
       Integer cantidad = Integer.parseInt(txtCantidad7.getText());
       String resultado = String.valueOf(restar(cantidad));
       txtCantidad7.setText(resultado);
    }//GEN-LAST:event_botonResta7ActionPerformed

    private void botonResta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResta5ActionPerformed
        // TODO add your handling code here:
       Integer cantidad = Integer.parseInt(txtCantidad5.getText());
       String resultado = String.valueOf(restar(cantidad));
       txtCantidad5.setText(resultado);
    }//GEN-LAST:event_botonResta5ActionPerformed

    private void botonResta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResta1ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(txtCantidad1.getText());
        String resultado = String.valueOf(restar(cantidad));
        txtCantidad1.setText(resultado);
    }//GEN-LAST:event_botonResta1ActionPerformed

    private void botonResta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResta2ActionPerformed
        // TODO add your handling code here:
       Integer cantidad = Integer.parseInt(txtCantidad2.getText());
       String resultado = String.valueOf(restar(cantidad));
       txtCantidad2.setText(resultado);
    }//GEN-LAST:event_botonResta2ActionPerformed

    private void botonResta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResta3ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(txtCantidad3.getText());
       String resultado = String.valueOf(restar(cantidad));
       txtCantidad3.setText(resultado);
    }//GEN-LAST:event_botonResta3ActionPerformed

    private void botonResta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResta4ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(txtCantidad4.getText());
       String resultado = String.valueOf(restar(cantidad));
       txtCantidad4.setText(resultado);
    }//GEN-LAST:event_botonResta4ActionPerformed

    private void botonResta8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResta8ActionPerformed
        // TODO add your handling code here:
       Integer cantidad = Integer.parseInt(txtCantidad8.getText());
       String resultado = String.valueOf(restar(cantidad));
       txtCantidad8.setText(resultado);
    }//GEN-LAST:event_botonResta8ActionPerformed

    private void txtCantidad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidad5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad5ActionPerformed

    private void txtCantidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad1ActionPerformed

    private void txtCantidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad2ActionPerformed

    private void txtCantidad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidad3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad3ActionPerformed

    private void txtCantidad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidad4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad4ActionPerformed

    private void txtCantidad8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidad8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad8ActionPerformed

    private void txtCantidad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidad7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad7ActionPerformed

    private void txtCantidad6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidad6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad6ActionPerformed

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        // TODO add your handling code here:
    
        Login1 nuevoInicio = new Login1();
        this.setVisible(false);
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    private void botonCancelarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarCompraActionPerformed
        // TODO add your handling code here:
        txtCantidad1.setText("0");
        txtCantidad2.setText("0");
        txtCantidad3.setText("0");
        txtCantidad4.setText("0");
        txtCantidad5.setText("0");
        txtCantidad6.setText("0");
        txtCantidad7.setText("0");
        txtCantidad8.setText("0");
    }//GEN-LAST:event_botonCancelarCompraActionPerformed

    private void botonSuma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSuma1ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(txtCantidad1.getText());
        String resultado = String.valueOf(sumar(cantidad));
        txtCantidad1.setText(resultado);
    }//GEN-LAST:event_botonSuma1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(txtCantidad2.getText());
        String resultado = String.valueOf(sumar(cantidad));
        txtCantidad2.setText(resultado);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(txtCantidad3.getText());
        String resultado = String.valueOf(sumar(cantidad));
        txtCantidad3.setText(resultado);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    public int sumar (int cantidad){
        cantidad = cantidad + 1;
        return cantidad;
    }
     public int restar (int cantidad){
      if(cantidad>0){
          cantidad = cantidad - 1;
      }
      return cantidad;
     }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelarCompra;
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonPagar;
    private javax.swing.JButton botonResta1;
    private javax.swing.JButton botonResta2;
    private javax.swing.JButton botonResta3;
    private javax.swing.JButton botonResta4;
    private javax.swing.JButton botonResta5;
    private javax.swing.JButton botonResta6;
    private javax.swing.JButton botonResta7;
    private javax.swing.JButton botonResta8;
    private javax.swing.JButton botonSuma1;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCantidad1;
    private javax.swing.JTextField txtCantidad2;
    private javax.swing.JTextField txtCantidad3;
    private javax.swing.JTextField txtCantidad4;
    private javax.swing.JTextField txtCantidad5;
    private javax.swing.JTextField txtCantidad6;
    private javax.swing.JTextField txtCantidad7;
    private javax.swing.JTextField txtCantidad8;
    // End of variables declaration//GEN-END:variables
}
