CREATE TABLE 'Articulos' (
'id' INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
'NOMBRE' TEXT NOT NULL ,
'DESCRIPCION' TEXT NOT NULL ,
'STOCK' REAL NOT NULL ,
'id_Categoria' INTEGER NOT NULL ,
'id_Proveedores' INTEGER NOT NULL  REFERENCES 'Proveedores' ('id')
);

CREATE TABLE 'Proveedores' (
'id' INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
'PNombre' TEXT NOT NULL ,
'PDireccion' TEXT NOT NULL ,
'NTelefono' TEXT NOT NULL 
);

CREATE TABLE 'Entrada' (
'id' INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
'Cantidad' REAL NOT NULL ,
'Precio' INTEGER NOT NULL ,
'Total' REAL NOT NULL ,
'id_Articulos' INTEGER NOT NULL  REFERENCES 'Articulos' ('id')
);

CREATE TABLE 'Clientes' (
'id' INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
'CNombre' TEXT NOT NULL ,
'CDireccion' TEXT NOT NULL ,
'CTelefono' TEXT NOT NULL 
);

CREATE TABLE 'Salida' (
'id' INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
'CantidadVenta' REAL NOT NULL ,
'PrecioUnitario' INTEGER NOT NULL ,
'TotalVenta' REAL NOT NULL ,
'id_Articulos' INTEGER NOT NULL  REFERENCES 'Articulos' ('id'),
'id_Clientes' INTEGER NOT NULL  REFERENCES 'Clientes' ('id')
);